---
- hosts: git
  become: true
  become_user: root
  tasks:
  - name: add a group
    group: name={{ item }} state=present
    with_items:
     - sunil
    tags: add_new_group
  - name: add serveral users
    user: name={{ item }} state=present group=sunil shell=/bin/bash
    with_items:
     - supriya
     - lucky
    tags: add_new_user
  - name: generate ssh keys
    user: name={{ item }} generate_ssh_key=yes ssh_key_bits=4096 ssh_key_file=.ssh/id_rsa
    with_items:
     - supriya
     - lucky
    tags: genarate_ssh_keys
  - name: delete user
    user: name={{ item }} state=absent
    with_items:
     - supriya
     - lucky
     - sunil
    tags: delete_user
  - name: delete groups
    group: name={{ item }} state=absent
    with_items:
     - sunil
    tags: delete_groups
